### ISSUE TITLE
Android 怎么读？

### ISSUE THREAD

**Issue by alexliubj** [everettjf/TomatoRead#11]
web 版本不开放了？如何批量导入到其他RSS阅读器呢？

**Comment by everettjf** [comment]
不好意思。web版本没有计划长期开放。最近一直忙别的，服务器到期后没有续费 :)

导入目前没有自动方案。不过，数据都在这里：

https://github.com/everettjf/everettjf.github.com/tree/master/app/blogreader

你可以看看自己写个小脚本做成其他rss阅读器支持的格式。

**Comment by alexliubj** [comment]
有没有到处的rss 列表？想在android 其他阅读器订阅呢。

**Comment by everettjf** [comment]
https://github.com/everettjf/everettjf.github.com/blob/master/app/blogreader/1_feeds.json

你看看这个。我没怎么深入用过其他RSS阅读器，不太清楚导入格式。

**Comment by alexliubj** [comment]
Thx, bro.
