### ISSUE TITLE
snows.link试用体验反馈

### ISSUE THREAD

**Issue by chuanyi** [everettjf/TomatoRead#3]
功能不多，简单反馈：
### 需求

你的用户故事里面，定位高质量博客搜藏，表面需求正确；

但真实需求 内容 大于 首页，我看到高质量博客都是一次性全部翻完（不一定细看），对其中好文直接evernote剪藏起来，然后随时随地打开慢慢消化或分好类别珍藏（内容获取结束，不再依赖）；

如果对博主感兴趣，期望的形式是RSS订阅，即便我很闲的时候也不愿意把千把个网址一个个点开看是否有更新；而且越高质量博客，更新频率就越低；更新很频繁的自媒体信息时效价值大，内容搜藏价值就会降低（可沉淀知识少）；

如果snows.link定位不同需求的冷门稀缺资源搜藏，那更倾向于“知识库”的思路，也就是云笔记的做法，光搜藏首页链接远远不够；

如果snows.link定位对每天都要打开大量网站的用户来说，那更倾向于“浏览器“的思路，在浏览器首页最近访问网站里按历史访问频率排序就好了；

一句话概括就是：非刚需（替代品多）、价值有限。

但是未来版本snows.link有社区计划，工具->社区 转型，价值可能就不一样了，后端既有高质量博客入口集（有分类、有专业人士整理推荐）、又有活跃博主及大量粉丝。
### 设计

首页打开，内容展示很乱。接触snows.link的人应该是从首页开始上手，肯定得弄好点；
打开某人的公开链接页面，分类查看体验差：
    Filter条件点一个都是且关系，每次都得删掉所有filter，重新选择，繁琐；
    tag和topic很多时，页面滚到下面，搜索结果已高高在上看不见，得滚动页面再上去；

Chrome插件使用问题：
    每天使用时，都得重新login with github，不能永远记住么,session有效期太短了；
    快捷搜藏页面建议美化一下，丑了点；
    雪花图标做的很漂亮，赞一个；

是否应该提供从浏览器现有网址收藏夹导入的功能，因为大部分人已经珍藏了一大片了；

有两本小书《交互设计4策略》《写给大家看的设计书》建议看看，几个简单的原则就能弄出基本简洁、清新的页面。

先这些，以后想到再补。

**Comment by everettjf** [comment]
十分十分感谢。我好好思考下这些问题。
下一版本正在私有库中开发中，到时候再体验下哈。

**Comment by everettjf** [comment]
改为 http://iosblog.cc 在个人维护及使用范围内。马上开始iOS客户端开发。
