### ISSUE TITLE
1.3版本计划

### ISSUE THREAD

**Issue by everettjf** [everettjf/TomatoRead#8]
1. 博文列表 副标题颜色太浅
2. 订阅 最后更新时间获取错误
3. 订阅 的博客无法同步服务器的删除操作（服务器删除某一博客后，App不能同步删除）

**Comment by xhzengAIB** [comment]
不要脸的提交我的Blog链接，哈哈！  http://zengxianhua.com

**Comment by everettjf** [comment]
@xhzengAIB 感谢前辈
